name: Deploiement en continu

on:
    push:
        branches: [master]

jobs:
    version:
        runs-on: ubuntu-latest
        if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
            - run: git config --global user.name '${{ secrets.GH_PUBLIC_NAME }}'
            - run: git config --global user.email '${{ secrets.GH_EMAIL }}'
            - run: npm version patch -m "[RELEASE] %s"
            - run: git push
            - run: git push --tags
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 12
            - run: npm i
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
    deploy:
      name: 🚀 Deploy
      runs-on: ubuntu-latest
      steps:
        - name: Install dependencies
        - uses: actions/checkout@v2
        - run: npm ci
        - run: npm run build storybook
        - name: 📂 Sync files
          uses: ./
          with:
            server: ${{ secrets.FTP_SERVOR }}
            username: ${{ secrets.USERNAME_FTP }}
            password: ${{ secrets.FTP_PASSWORD }}
            local-dir: ./storybook-static
            protocol: ftps
            port: 21